{{- if eq .Values.deployment.strategy "abTesting" -}}
apiVersion: argoproj.io/v1alpha1
kind: Experiment
metadata:
  name: {{ include "web-service.fullname" . }}
spec:
  duration: {{ .Values.deployment.abTestingConfig.duration }}
  progressDeadlineSeconds: 30
  templates:
    - name: ab-test
      replicas: {{ .Values.deployment.abTestingConfig.replicas }}
      selector:
        matchLabels:
          app.kubernetes.io/name: {{ include "web-service.name" . }}
          app.kubernetes.io/instance: {{ .Release.Name }}
          ab-test: "true"
      template:
        metadata:
          labels:
            app.kubernetes.io/name: {{ include "web-service.name" . }}
            app.kubernetes.io/instance: {{ .Release.Name }}
            ab-test: "true"
        spec:
          containers:
            - name: {{ .Chart.Name }}
              securityContext: {{- toYaml .Values.securityContext | nindent 16 }}
              image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
              imagePullPolicy: {{ .Values.image.pullPolicy }}
              env:
                - name: DATABASE_HOST
                  valueFrom:
                    secretKeyRef:
                      name: {{ .Values.databaseSecret.name }}
                      key: {{ .Values.databaseSecret.hostKey }}
                - name: DATABASE_NAME
                  value: {{ .Values.databaseName }}
                - name: DATABASE_USERNAME
                  valueFrom:
                    secretKeyRef:
                      name: {{ .Values.databaseSecret.name }}
                      key: {{ .Values.databaseSecret.usernameKey }}
                - name: DATABASE_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: {{ .Values.databaseSecret.name }}
                      key: {{ .Values.databaseSecret.passwordKey }}
              ports:
                - name: http
                  containerPort: 8080
                  protocol: TCP
              {{- with .Values.livenessProbe }}
              livenessProbe:
                {{- toYaml . | nindent 16 }}
              {{- end }}
              {{- with .Values.readinessProbe }}
              readinessProbe: {{- toYaml . | nindent 16 -}}
              {{- end }}
              resources:
                {{- toYaml .Values.resources | nindent 16 }}
          {{- with .Values.nodeSelector }}
          nodeSelector:
            {{- toYaml . | nindent 8 }}
          {{- end }}
          {{- with .Values.affinity }}
          affinity:
            {{- toYaml . | nindent 8 }}
          {{- end }}
          {{- with .Values.tolerations }}
          tolerations:
            {{- toYaml . | nindent 8 }}
          {{- end }}
  analyses:
    {{- range .Values.deployment.abTestingConfig.analysisTemplates }}
    - name: {{ . }}
      templateName: compare
      requiredForCompletion: true
      args:
        - name: service-name
          value: {{ print (include "web-service.fullname" $) "-ab-test" }}
    {{- end }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ print (include "web-service.fullname" .) "-ab-test" }}
  labels:
    {{- include "web-service.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ include "web-service.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    ab-test: "true"
{{- end }}
