apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: {{ include "web-service.fullname" . }}
  labels:
    {{- include "web-service.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.deployment.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "web-service.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  revisionHistoryLimit: 3
  strategy:
    {{- if eq .Values.deployment.strategy "blueGreen" }}
    blueGreen:
      activeService: {{ include "web-service.fullname" . }}
      previewService: {{ print (include "web-service.fullname" .) "-preview" }}
      maxUnavailable: {{ .Values.deployment.maxUnavailable }}
      autoPromotionEnabled: {{ .Values.deployment.blueGreenConfig.autoPromotionEnabled }}
      autoPromotionSeconds: {{ default 300 .Values.deployment.blueGreenConfig.autoPromotionSeconds }}
      previewReplicaCount: {{ .Values.deployment.blueGreenConfig.previewReplicaCount }}
      scaleDownDelaySeconds: {{ .Values.deployment.blueGreenConfig.scaleDownDelaySeconds }}
      {{- if gt (len .Values.deployment.blueGreenConfig.prePromotionAnalysis) 0 }}
      prePromotionAnalysis:
        templates:
          {{- range .Values.deployment.blueGreenConfig.prePromotionAnalysis }}
          - templateName: {{ . }}
          {{- end }}
        args:
          - name: service-name
            value: {{ print (include "web-service.fullname" .) "-preview" }}
      {{- end }}
      {{- if gt (len .Values.deployment.blueGreenConfig.postPromotionAnalysis) 0 }}
      postPromotionAnalysis:
        templates:
          {{- range .Values.deployment.blueGreenConfig.postPromotionAnalysis }}
          - templateName: {{ . }}
          {{- end }}
        args:
          - name: service-name
            value: {{ include "web-service.fullname" . }}
      {{- end }}
    {{- else if eq .Values.deployment.strategy "canary" }}
    canary:
      stableService: {{ include "web-service.fullname" . }}
      canaryService: {{ print (include "web-service.fullname" .) "-canary" }}
      maxUnavailable: {{ .Values.deployment.maxUnavailable }}
      maxSurge: {{ .Values.deployment.canaryConfig.maxSurge }}
      steps:
        {{- toYaml .Values.deployment.canaryConfig.steps | nindent 8 }}
      analysis:
        templates:
          {{- range .Values.deployment.canaryConfig.analysisTemplates }}
          - templateName: {{ . }}
          {{- end }}
        startingStep: {{ .Values.deployment.canaryConfig.analysisStartingStep }}
        args:
          - name: service-name
            value: {{ print (include "web-service.fullname" .) "-canary" }}
    {{- else }}
    canary:
      maxSurge: {{ .Values.deployment.rollingUpdateConfig.maxSurge }}
      maxUnavailable: {{ .Values.deployment.maxUnavailable }}
    {{- end }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "web-service.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          securityContext: {{- toYaml .Values.securityContext | nindent 12 }}
          image: {{ printf "%s:%s" .Values.image.repository .Values.image.tag }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: DATABASE_HOST
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.databaseSecret.name }}
                  key: {{ .Values.databaseSecret.hostKey }}
            - name: DATABASE_NAME
              value: {{ .Values.databaseName }}
            - name: DATABASE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.databaseSecret.name }}
                  key: {{ .Values.databaseSecret.usernameKey }}
            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.databaseSecret.name }}
                  key: {{ .Values.databaseSecret.passwordKey }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          {{- with .Values.livenessProbe }}
          livenessProbe:
            {{- toYaml . | nindent 12 -}}
          {{- end }}
          {{- with .Values.readinessProbe }}
          readinessProbe:
            {{- toYaml . | nindent 12 -}}
          {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 -}}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 -}}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 -}}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 -}}
      {{- end }}
