{{- if contains .Values.deployment.strategy "blueGreen,canary" -}}
apiVersion: v1
kind: Service
metadata:
  {{- if eq .Values.deployment.strategy "blueGreen" }}
  name: {{ print (include "web-service.fullname" .) "-preview" }}
  {{- else if eq .Values.deployment.strategy "canary" }}
  name: {{ print (include "web-service.fullname" .) "-canary" }}
  {{- end }}
  labels:
    {{- include "web-service.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ include "web-service.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
---
{{- end -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "web-service.fullname" . }}
  labels:
    {{- include "web-service.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ include "web-service.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
