{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "web-service.serviceAccountName" . }}
  labels:
    {{- include "web-service.labels" . | nindent 4 }}
{{- end -}}
